//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class CounterSale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CounterSale()
        {
            this.CounterSalesInvoiceAmountDetails = new HashSet<CounterSalesInvoiceAmountDetail>();
            this.CounterSalesTrans = new HashSet<CounterSalesTran>();
        }
    
        public long ID { get; set; }
        public string TransNo { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> PaymentTypeID { get; set; }
        public string ReferenceNo { get; set; }
        public string CustomerName { get; set; }
        public Nullable<int> Age { get; set; }
        public string PhoneNo { get; set; }
        public string Address { get; set; }
        public Nullable<int> DoctorID { get; set; }
        public Nullable<int> WarehouseID { get; set; }
        public Nullable<decimal> GrossAmount { get; set; }
        public Nullable<decimal> DiscountAmt { get; set; }
        public Nullable<decimal> TaxableAmt { get; set; }
        public Nullable<bool> IsDraft { get; set; }
        public Nullable<decimal> SGSTAmount { get; set; }
        public Nullable<decimal> CGSTAmount { get; set; }
        public Nullable<decimal> IGSTAmount { get; set; }
        public Nullable<decimal> RoundOff { get; set; }
        public Nullable<decimal> NetAmount { get; set; }
        public Nullable<decimal> BalanceAmount { get; set; }
        public Nullable<bool> IsCancelled { get; set; }
        public Nullable<System.DateTime> CancelledDate { get; set; }
        public Nullable<decimal> GSTAmount { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> CreatedUserID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> FinYear { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<int> ApplicationID { get; set; }
        public string PartyName { get; set; }
        public Nullable<int> PatientID { get; set; }
        public Nullable<decimal> PackingPrice { get; set; }
        public Nullable<decimal> TotalAmountReceived { get; set; }
        public Nullable<decimal> BalanceToBePaid { get; set; }
        public Nullable<int> PaymentModeID { get; set; }
        public decimal CessAmount { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> SalesType { get; set; }
        public Nullable<bool> ReturnMet { get; set; }
        public Nullable<int> BankID { get; set; }
        public string DoctorName { get; set; }
        public int DiscountCategoryID { get; set; }
        public Nullable<int> CurrencyID { get; set; }
        public Nullable<int> IsVAT { get; set; }
        public Nullable<int> IsGST { get; set; }
        public Nullable<decimal> TotalVATAmount { get; set; }
        public string CivilID { get; set; }
        public string MobileNumber { get; set; }
        public decimal DiscountPercentage { get; set; }
        public bool PrintWithItemName { get; set; }
        public Nullable<int> ContactID { get; set; }
        public Nullable<bool> IsGoodsReceived { get; set; }
        public string ReferenceCode { get; set; }
        public Nullable<decimal> AmountReceived { get; set; }
        public Nullable<decimal> VATPercentage { get; set; }
        public string ReceiverBankName { get; set; }
        public Nullable<decimal> BankCharges { get; set; }
        public string BankInstrumentNumber { get; set; }
        public string ChecqueDate { get; set; }
        public Nullable<int> ReceiverBankID { get; set; }
        public Nullable<int> VATPercentageID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CounterSalesInvoiceAmountDetail> CounterSalesInvoiceAmountDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CounterSalesTran> CounterSalesTrans { get; set; }
    }
}
