//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockIssueTemplateItem
    {
        public int ID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<int> IssuePremiseID { get; set; }
        public Nullable<int> BatchTypeID { get; set; }
        public Nullable<decimal> IssueQty { get; set; }
        public Nullable<int> UnitID { get; set; }
    }
}
