using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net;
using System.Net.Mail;
using System.Text;
using BusinessLayer;
using BusinessObject;
using PresentationContractLayer;
using System.IO;

namespace TradeSuiteApp.Web.Areas.Admin.Controllers
{ 
    public class MailController : Controller
    {
    private IGeneralContract generalBL;

    public MailController()
    {
        generalBL = new GeneralBL();
    }
    // GET: Admin/Mail
    public ActionResult Index()
        {
            return View();
        }
        public JsonResult SendMailToUser(string url,string ui, int id, string subject, string body,string TomailID)
        {
            bool result = false;
              bool ismailSent = generalBL.GetMailReceiverDetails(ui, id).FirstOrDefault().IsMailSent;
            if (!ismailSent)
            {
                // string Receiver = generalBL.GetMailReceiverDetails(ui, id).FirstOrDefault().ReceiverMailID.ToString();

                string Receiver = TomailID;
                //string Subject = "Automaticaly generated";
                //string Body = "<P>This is an automaticaly generated mail.</P> ";
                result = SendMail(Receiver, subject, body, url,ui,id);
              
            }
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        public bool SendMail(string Receiver, string Subject, string Body,string url,string ui, int id)
        {
            try
            {
                string SenderMail =generalBL.GetMailSenderDetails("purchase").FirstOrDefault().SenderMailID.ToString();
                string SenderPassword = generalBL.GetMailSenderDetails("purchase").FirstOrDefault().SenderMailPassword.ToString();
                //SenderPassword is generted from Google Accountss Settings' App Password(Previously 'Less Secure Apps')
                //Here, SenderPassword is not Gmail Password.It is generated by google and configured in 'MailDetails' Table
                string CC = generalBL.GetConfig("MailCC");

                SmtpClient Client = new SmtpClient("smtp.gmail.com", 587);
                Client.EnableSsl = true;
                Client.Timeout = 100000;
                Client.DeliveryMethod = SmtpDeliveryMethod.Network;
                Client.UseDefaultCredentials = false;
                Client.Credentials = new NetworkCredential(SenderMail, SenderPassword);
                MailMessage message = new MailMessage(SenderMail, Receiver, Subject, Body);
                message.IsBodyHtml = true;
                message.BodyEncoding = UTF8Encoding.UTF8;
                System.Net.Mail.Attachment attachment;
                string FilePath = Path.Combine(Server.MapPath(url));

                attachment = new System.Net.Mail.Attachment(FilePath);
                message.Attachments.Add(attachment);
                message.CC.Add(CC);
                //Client.EnableSsl = true;
                Client.Send(message);
                generalBL.UpdateMailSent(ui, id);
                return true;
            }
            catch (Exception ex)
            {
                return false;
            }
        }
    }
}